### ISSUE TITLE
get_models cannot find the model list

### ISSUE THREAD

**Issue by sachnun** [ading2210/vercel-llm-api#10]
I think there was a change in the js source code, so the regex path is invalid
```python
Traceback (most recent call last):
  File "/home/dakunesu/vercel-llm-api/generate.py", line 7, in <module>
    client = vercel_ai.Client()
  File "/home/dakunesu/vercel-llm-api/vercel_ai.py", line 40, in __init__
    self.model_ids = list(self.models.keys())
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by ading2210** [comment]
I'm investigating this right now.

**Comment by VanshShah1** [comment]
I'm getting the same error

**Comment by ading2210** [comment]
Vercel changed the way the anti-bot token was encoded. It'll take a bit to reverse engineer.

**Comment by sachnun** [comment]
> Vercel changed the way the anti-bot token was encoded. It'll take a bit to reverse engineer.

I don't know how to grab the model from the original source, 
so i tried it locally (force to models.json that I created during caching) 

and I also found a token change, but it is still on a bs64, just character set has changed. 

```python
token_data[2] = "mark" # replace to mark
token = {"r": token_data, "t": data["t"]}
token_string = json.dumps(
  token,
  separators=(",", ":"),
).encode("utf-16le") # encode with utf-16le
return base64.b64encode(token_string).decode()
```

hope this can help you

**Comment by VanshShah1** [comment]
> Vercel changed the way the anti-bot token was encoded. It'll take a bit to reverse engineer.

How much time will it take? I need it urgently for a project.

**Comment by ading2210** [comment]
@sachnun Simply encoding it as `utf-16-le` doesn't work. Certain Javascript quirks have to be replicated, and `quickjs` doesn't seem to work.

**Comment by sachnun** [comment]
@ading2210 in my case, its works basically.

![image](https://github.com/ading2210/vercel-llm-api/assets/24667698/bc4a56d0-71e1-40b7-953f-4582217d9734)

**Comment by ading2210** [comment]
@sachnun Even with that it still doesn't seem to be fully reliable. 2/3 of the time the server still rejects the requests.

**Comment by ading2210** [comment]
It looks like the failed requests are due to some sort of rate limit, so the token implementation is fine.

**Comment by ading2210** [comment]
v0.3.1 contains the fix.

**Comment by VanshShah1** [comment]
Thanks a lot bro. Love you all.

**Comment by sachnun** [comment]
> @sachnun Even with that it still doesn't seem to be fully reliable. 2/3 of the time the server still rejects the requests.

well, for that I added an event handler to repeat the error

**Comment by VanshShah1** [comment]
any update with the Request Error 500?

**Comment by VanshShah1** [comment]
File "/Users/vanshshah/Documents/GitHub/neurumtopsecret/experiments/nerdapi.py", line 16, in ask
    for chunk in client.generate("openai:gpt-3.5-turbo", f"Your name is n.e.r.d., an AI language model trained by Neurum. {prompt}", params=params):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vercel_ai.py", line 185, in generate
    for chunk in self.stream_request(self.session.post, self.generate_url, headers=headers, json=payload):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vercel_ai.py", line 144, in stream_request
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vercel_ai.py", line 132, in request_thread
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/curl_cffi/requests/cookies.py", line 51, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 500:
