### ISSUE TITLE
Token limit?

### ISSUE THREAD

**Issue by ChicoYildiz** [ading2210/vercel-llm-api#15]
The AI seems to cut off at about, according to tokenizer, 256 tokens. (even though default params state 500)

I've already tried changing the parameters, no success..

something like this doesn't work:

```python
client.models["openai:gpt-3.5-turbo"]["parameters"]["maximumLength"]["value"] = 10000
client.model_defaults["openai:gpt-3.5-turbo"]["maximumLength"] = 10000
```

neither does this:

```python
defaults['maximumLength'] = 5000 # modyfying source
```

So, is the token limit fixed by Vercel?

**Comment by 0x6a69616e** [comment]
Vercel AI uses `maxTokens` instead of `maximumLength` within request payloads. Perhaps this may be causing the issue?

![image](https://github.com/ading2210/vercel-llm-api/assets/62970770/f30b5164-45e2-4cf7-8d6d-4aa1a9250340)
