### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by mohcenlaaroussi** [ading2210/vercel-llm-api#19]
I keep getting HTTP error 429 , does anybody kow why?

**Comment by Ivang71** [comment]
Vercel backend sees that you make too many requests from one ip and temporarily bans it.

**Comment by revolutionarycomrade** [comment]
I'm also experiencing the same issue, and it happens on proxies with very few, if any, requests made to vercel. Notably, I can still get responses from vercel using a regular browser session without an account, but attempting to use the api results in the ```HTTP Error 429```.

**Comment by ading2210** [comment]
Closing this in favor of #22.
