### ISSUE TITLE
HTTP Error 500 when token-streaming

### ISSUE THREAD

**Issue by ChicoYildiz** [ading2210/vercel-llm-api#7]
[error codes here](https://imgur.com/a/tzDo53c)

**Comment by kapitankuba20111** [comment]
It's normal, just try again

**Comment by ChicoYildiz** [comment]
> It's normal, just try again

Fair enough, but isn’t there a way to not stream tokens and just get a response when it’s done?

**Comment by ading2210** [comment]
> Fair enough, but isn’t there a way to not stream tokens and just get a response when it’s done?
@Recentaly 

Yes, you can just join together the received chunks.

```python
result = ""
for chunk in client.generate("openai:gpt-3.5-turbo", "Summarize the GNU GPL v3"):
  result += chunk
print(result)
```

**Comment by ChicoYildiz** [comment]
> > Fair enough, but isn’t there a way to not stream tokens and just get a response when it’s done?
> > @Recentaly
> 
> Yes, you can just join together the received chunks.
> 
> ```python
> result = ""
> for chunk in client.generate("openai:gpt-3.5-turbo", "Summarize the GNU GPL v3"):
>   result += chunk
> print(result)
> ```

But wouldn’t this still utilize tokens? I get the bug either way sometimes. But what helps is lowering the size of my gigantic prompt.

**Comment by ading2210** [comment]
You can't avoid streaming the response, since Vercel returns the generated text using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).
